version: "3.8"

services:
  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'go-backend'
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/init.sql:ro
    command: --init-file /init.sql
