apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
    SET GLOBAL enforce_gtid_consistency = ON;
    SET GLOBAL gtid_mode = OFF_PERMISSIVE;
    SET GLOBAL gtid_mode = ON_PERMISSIVE;
    SET GLOBAL gtid_mode = ON;
    create table tasks
    (
        id      int auto_increment primary key,
        title   varchar(60)                         not null,
        created timestamp default CURRENT_TIMESTAMP null,
        updated timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP
    );